# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "openaq-status"
license = "MIT"
licenselink = "https://github.com/openaq/openaq-status/blob/master/LICENSE"
description = "OpenAQ status page theme"
homepage = "https://github.com/openaq/openaq-status"
tags = []
features = []
min_version = "0.68"

[author]
  name = "OpenAQ"
  homepage = "https://github.com/openaq/"
